version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: inscription
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      mynetwork:

  inscription-app:
    depends_on:
      - mysqldb
    image: wassimmanai/inscridocker
    restart: on-failure
    ports:
      - "8077:8077"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/inscription?autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    stdin_open: true
    tty: true
    networks:
      mynetwork:

  discovery-service:
    container_name: discovery-service
    build: ./Eureka-Server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      mynetwork:

volumes:
  db:

networks:
  mynetwork:
    driver: bridge
