version: '3'
services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inscription
    ports:
      - "3306:3306"
    networks:
      - myappNetwork
    volumes:
      - mysql-data:/var/lib/mysql

  # Spring Boot service
  springboot-app:
    image: wassimmanai/app:latest
    restart: on-failure
    ports:
      - "8086:8086"
    depends_on:
      - mysqldb
    networks:
      - myappNetwork
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/inscription?createDatabaseIfNotExist=true",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "root",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
      stdin_open: true
      tty: true

networks:
  myappNetwork:

volumes:
  mysql-data: